// Code generated by protoc-gen-go. DO NOT EDIT.
// source: character.proto

package character

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KilledMonsters struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Wanted               bool     `protobuf:"varint,3,opt,name=wanted,proto3" json:"wanted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KilledMonsters) Reset()         { *m = KilledMonsters{} }
func (m *KilledMonsters) String() string { return proto.CompactTextString(m) }
func (*KilledMonsters) ProtoMessage()    {}
func (*KilledMonsters) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d698b655df4d08, []int{0}
}

func (m *KilledMonsters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KilledMonsters.Unmarshal(m, b)
}
func (m *KilledMonsters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KilledMonsters.Marshal(b, m, deterministic)
}
func (m *KilledMonsters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KilledMonsters.Merge(m, src)
}
func (m *KilledMonsters) XXX_Size() int {
	return xxx_messageInfo_KilledMonsters.Size(m)
}
func (m *KilledMonsters) XXX_DiscardUnknown() {
	xxx_messageInfo_KilledMonsters.DiscardUnknown(m)
}

var xxx_messageInfo_KilledMonsters proto.InternalMessageInfo

func (m *KilledMonsters) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KilledMonsters) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *KilledMonsters) GetWanted() bool {
	if m != nil {
		return m.Wanted
	}
	return false
}

type Character struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64             `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Strength             int64             `protobuf:"varint,3,opt,name=strength,proto3" json:"strength,omitempty"`
	Vitality             int64             `protobuf:"varint,4,opt,name=vitality,proto3" json:"vitality,omitempty"`
	Agility              int64             `protobuf:"varint,5,opt,name=agility,proto3" json:"agility,omitempty"`
	Dexterity            int64             `protobuf:"varint,6,opt,name=dexterity,proto3" json:"dexterity,omitempty"`
	Intelligence         int64             `protobuf:"varint,7,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Luck                 int64             `protobuf:"varint,8,opt,name=luck,proto3" json:"luck,omitempty"`
	Hp                   int64             `protobuf:"varint,9,opt,name=hp,proto3" json:"hp,omitempty"`
	Mp                   int64             `protobuf:"varint,10,opt,name=mp,proto3" json:"mp,omitempty"`
	KilledMonsters       []*KilledMonsters `protobuf:"bytes,11,rep,name=killed_monsters,json=killedMonsters,proto3" json:"killed_monsters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Character) Reset()         { *m = Character{} }
func (m *Character) String() string { return proto.CompactTextString(m) }
func (*Character) ProtoMessage()    {}
func (*Character) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d698b655df4d08, []int{1}
}

func (m *Character) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Character.Unmarshal(m, b)
}
func (m *Character) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Character.Marshal(b, m, deterministic)
}
func (m *Character) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Character.Merge(m, src)
}
func (m *Character) XXX_Size() int {
	return xxx_messageInfo_Character.Size(m)
}
func (m *Character) XXX_DiscardUnknown() {
	xxx_messageInfo_Character.DiscardUnknown(m)
}

var xxx_messageInfo_Character proto.InternalMessageInfo

func (m *Character) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Character) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Character) GetStrength() int64 {
	if m != nil {
		return m.Strength
	}
	return 0
}

func (m *Character) GetVitality() int64 {
	if m != nil {
		return m.Vitality
	}
	return 0
}

func (m *Character) GetAgility() int64 {
	if m != nil {
		return m.Agility
	}
	return 0
}

func (m *Character) GetDexterity() int64 {
	if m != nil {
		return m.Dexterity
	}
	return 0
}

func (m *Character) GetIntelligence() int64 {
	if m != nil {
		return m.Intelligence
	}
	return 0
}

func (m *Character) GetLuck() int64 {
	if m != nil {
		return m.Luck
	}
	return 0
}

func (m *Character) GetHp() int64 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *Character) GetMp() int64 {
	if m != nil {
		return m.Mp
	}
	return 0
}

func (m *Character) GetKilledMonsters() []*KilledMonsters {
	if m != nil {
		return m.KilledMonsters
	}
	return nil
}

func init() {
	proto.RegisterType((*KilledMonsters)(nil), "character.KilledMonsters")
	proto.RegisterType((*Character)(nil), "character.Character")
}

func init() { proto.RegisterFile("character.proto", fileDescriptor_17d698b655df4d08) }

var fileDescriptor_17d698b655df4d08 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xa5, 0x49, 0xbf, 0x32, 0x2d, 0xad, 0x2c, 0x45, 0xd6, 0xe2, 0xa1, 0xf4, 0xd4, 0x53, 0x0f,
	0x15, 0x41, 0x05, 0x0f, 0x51, 0x2f, 0xe2, 0xc7, 0x21, 0x05, 0xaf, 0x12, 0x33, 0x43, 0xb3, 0x34,
	0xd9, 0x84, 0xed, 0xb6, 0xea, 0x6f, 0xf3, 0x6f, 0xf9, 0x03, 0x24, 0x9b, 0x8f, 0xb6, 0xe0, 0x25,
	0xb7, 0x7d, 0xef, 0xcd, 0x7b, 0x0c, 0x6f, 0x58, 0x18, 0x06, 0xa1, 0xaf, 0xfc, 0x40, 0x93, 0x9a,
	0xa7, 0x2a, 0xd1, 0x09, 0x73, 0x2a, 0x62, 0xfa, 0x0a, 0x83, 0x27, 0x11, 0x45, 0x84, 0x2f, 0x89,
	0xdc, 0x68, 0x52, 0x1b, 0x36, 0x00, 0x4b, 0x20, 0x6f, 0x4c, 0x1a, 0x33, 0xdb, 0xb3, 0x04, 0xb2,
	0x11, 0xb4, 0x82, 0x64, 0x2b, 0x35, 0xb7, 0x0c, 0x95, 0x03, 0x76, 0x0a, 0xed, 0x4f, 0x5f, 0x6a,
	0x42, 0x6e, 0x4f, 0x1a, 0xb3, 0xae, 0x57, 0xa0, 0xe9, 0x8f, 0x05, 0xce, 0x7d, 0x99, 0xce, 0x18,
	0x34, 0xa5, 0x1f, 0x93, 0x49, 0x73, 0x3c, 0xf3, 0x2e, 0xf2, 0xad, 0x2a, 0x7f, 0x0c, 0xdd, 0x8d,
	0x56, 0x24, 0x57, 0x3a, 0x34, 0x59, 0xb6, 0x57, 0xe1, 0x4c, 0xdb, 0x09, 0xed, 0x47, 0x42, 0x7f,
	0xf3, 0x66, 0xae, 0x95, 0x98, 0x71, 0xe8, 0xf8, 0x2b, 0x61, 0xa4, 0x96, 0x91, 0x4a, 0xc8, 0xce,
	0xc1, 0x41, 0xfa, 0xd2, 0xa4, 0x32, 0xad, 0x6d, 0xb4, 0x3d, 0xc1, 0xa6, 0xd0, 0x17, 0x52, 0x53,
	0x14, 0x89, 0x15, 0xc9, 0x80, 0x78, 0xc7, 0x0c, 0x1c, 0x71, 0xd9, 0xde, 0xd1, 0x36, 0x58, 0xf3,
	0xae, 0xd1, 0xcc, 0x3b, 0xdb, 0x3b, 0x4c, 0xb9, 0x93, 0xef, 0x1d, 0xa6, 0x19, 0x8e, 0x53, 0x0e,
	0x39, 0x8e, 0x53, 0x76, 0x07, 0xc3, 0xb5, 0x69, 0xf2, 0x3d, 0x2e, 0xaa, 0xe4, 0xbd, 0x89, 0x3d,
	0xeb, 0x2d, 0xce, 0xe6, 0xfb, 0xfe, 0x8f, 0xbb, 0xf6, 0x06, 0xeb, 0x23, 0xbc, 0xf8, 0xb5, 0xe0,
	0xa4, 0x6a, 0x6f, 0x49, 0x6a, 0x27, 0x02, 0x62, 0xd7, 0xd0, 0x73, 0x11, 0x97, 0x65, 0x27, 0xa3,
	0x83, 0xb8, 0x6a, 0x76, 0xfc, 0x2f, 0x5b, 0x58, 0xdf, 0xca, 0xca, 0xea, 0x58, 0x6f, 0xa0, 0xef,
	0x22, 0x3e, 0x54, 0xb5, 0xd5, 0xf1, 0x5e, 0x01, 0xb8, 0x88, 0x6e, 0x71, 0x8e, 0x3a, 0xce, 0x5b,
	0x18, 0xba, 0x88, 0x8f, 0x87, 0xb7, 0xa8, 0x63, 0xbf, 0x84, 0x8e, 0x8b, 0xf8, 0x9c, 0x9d, 0xab,
	0x86, 0xed, 0xa3, 0x6d, 0xbe, 0xc5, 0xc5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x51, 0x93,
	0xd2, 0x29, 0x03, 0x00, 0x00,
}
